import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LIST = [
  { id:1, title:"Home", url:"/" },
  { id:2, title:"About", url:"/about" },
  { id:3, title:"Contact", url:"/Contact" },
  { id:4, title:"Cart", url:"/Cart" },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <Navbar data={LIST}/>
      <body>{children}</body>
    </html>
  );
}